[package]
name = "junk-spider"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
dotenv.workspace = true
futures.workspace = true
lazy_static = "1.5.0"
reqwest.workspace = true
serde.workspace = true
tokio.workspace = true
tokio-postgres.workspace = true
tracing.workspace = true
