[package]
name = "junk-server"
edition = "2021"
version.workspace = true
readme.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.9.0"
deadpool-postgres.workspace = true
dotenv.workspace = true
serde.workspace = true
tokio-postgres.workspace = true
utoipa = "5.3.1"
utoipa-redoc = { version = "6.0.0", features = ["actix-web"] }
