[package]
name = "junk-scraper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv.workspace = true
reqwest = "0.12.9"
tokio-postgres = "0.7.12"
tracing.workspace = true
