version: '3.8'

services:
  postgres:
    image: postgres:17.2
    container_name: junkyard
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: findump
    ports:
      - "7001:7001"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
