-- CREATE SCHEMA IF NOT EXISTS bond;
-- CREATE SCHEMA IF NOT EXISTS commodities;
CREATE SCHEMA IF NOT EXISTS common;
CREATE SCHEMA IF NOT EXISTS crypto;
CREATE SCHEMA IF NOT EXISTS econ;
-- CREATE SCHEMA IF NOT EXISTS forex;
CREATE SCHEMA IF NOT EXISTS stock;

CREATE SCHEMA IF NOT EXISTS test;
